wandb_version: 1

lr_schedulers:
  value:
    lambda:
      factor: 2
      step_size: 7
    step:
      gamma: 0.31463725910918433
      step_size: 8
models:
  value:
    DINCAE:
      interp_mode: nearest
training:
  value:
    batch_size: 32
    clip_value: 5
    dataset_idx: 1
    epochs: 3
    learning_rate: 0.00010660266220831608
    loss_kind: per_pixel_mse
    lr_scheduler: lambda
    model_kind: DINCAE_pconvs
    n_days: 9
    optimizer_kind: adam
    placeholder: 300
    save_every: 1
    scale_every: 5
    train_perc: 0.8
