method: bayes
metric:
  goal: minimize
  name: test_loss
parameters:
  lr_schedulers:
    parameters:
      lambda:
        parameters:
          factor:
            distribution: categorical
            values:
            - 2
          step_size:
            distribution: int_uniform
            max: 20
            min: 5
      step:
        parameters:
          gamma:
            distribution: uniform
            max: 0.8
            min: 0.2
          step_size:
            distribution: int_uniform
            max: 8
            min: 2
  models:
    parameters:
      DINCAE:
        parameters:
          interp_mode:
            distribution: categorical
            values:
            - nearest
  training:
    parameters:
      batch_size:
        distribution: categorical
        values:
        - 32
      clip_value:
        distribution: categorical
        values:
        - 5
      dataset_idx:
        distribution: int_uniform
        max: 2
        min: 1
      epochs:
        distribution: categorical
        values:
        - 200
      learning_rate:
        distribution: uniform
        max: 0.0002
        min: 5e-05
      loss_kind:
        distribution: categorical
        values:
        - per_pixel_mse
      lr_scheduler:
        distribution: categorical
        values:
        - lambda
      model_kind:
        distribution: categorical
        values:
        - DINCAE_pconvs
      n_days:
        distribution: categorical
        values:
        - 9
      optimizer_kind:
        distribution: categorical
        values:
        - adam
      placeholder:
        distribution: categorical
        values:
        - 300
      save_every:
        distribution: categorical
        values:
        - 1
      scale_every:
        distribution: int_uniform
        max: 10
        min: 3
      train_perc:
        distribution: categorical
        values:
        - 0.8
program: src/train.py