_wandb:
    value:
        cli_version: 0.21.1
        e:
            poctqixym0g220pk229su7a09u9qdsnk:
                codePath: src/train.py
                codePathLocal: src/train.py
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "250685575168"
                        used: "153745240064"
                email: lisadavinchie@gmail.com
                executable: /Users/lisadavinchie/Documents/University/Thesis/Land_data_inpainting/venv_inpainting/bin/python3
                git:
                    commit: bfe1f6be3a5f5bef00c5b824e8bb761c534a5413
                    remote: git@github.com:LisaDaVinchie/Land_data_inpainting.git
                host: client-222-14.vpn.units.it
                memory:
                    total: "8589934592"
                os: macOS-13.7.7-x86_64-i386-64bit
                program: /Users/lisadavinchie/Documents/University/Thesis/Land_data_inpainting/src/train.py
                python: CPython 3.11.8
                root: /Users/lisadavinchie/Documents/University/Thesis/Land_data_inpainting
                startedAt: "2025-08-17T08:38:50.021559Z"
                writerId: poctqixym0g220pk229su7a09u9qdsnk
        m: []
        python_version: 3.11.8
        t:
            "1":
                - 1
                - 54
            "2":
                - 1
                - 54
            "3":
                - 13
                - 16
            "4": 3.11.8
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-x86_64
batch_size:
    value: 32
dataset:
    value: dataset.nc
epochs:
    value: 10
learning_rate:
    value: 0.00058
loss_function:
    value: PerPixelMSE
model:
    value: DINCAE_pconvs
results_path:
    value: result_393.txt
weights_path:
    value: weights_393.pt
