_wandb:
    value:
        cli_version: 0.21.0
        e:
            lnu66iqx3qrvctbbhtos5m9e1czc5ajh:
                args:
                    - --paths
                    - src/paths.json
                    - --params
                    - src/params.json
                codePath: src/trainL.py
                codePathLocal: src/trainL.py
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "250685575168"
                        used: "229903519744"
                executable: /Users/lisadavinchie/Documents/University/Thesis/Land_data_inpainting/venv_inpainting/bin/python3
                git:
                    commit: bfe1f6be3a5f5bef00c5b824e8bb761c534a5413
                    remote: git@github.com:LisaDaVinchie/Land_data_inpainting.git
                host: cli-10-110-1-152.WIFIeduroamSTUD.units.it
                memory:
                    total: "8589934592"
                os: macOS-13.7.6-x86_64-i386-64bit
                program: /Users/lisadavinchie/Documents/University/Thesis/Land_data_inpainting/src/trainL.py
                python: CPython 3.11.8
                root: /Users/lisadavinchie/Documents/University/Thesis/Land_data_inpainting
                startedAt: "2025-07-07T16:31:02.919582Z"
                writerId: lnu66iqx3qrvctbbhtos5m9e1czc5ajh
        m: []
        python_version: 3.11.8
        t:
            "1":
                - 1
                - 41
                - 106
            "2":
                - 1
                - 41
                - 106
            "3":
                - 2
            "4": 3.11.8
            "5": 0.21.0
            "12": 0.21.0
            "13": darwin-x86_64
